CREATE TABLE role_prefixes (
    prefix      TEXT         PRIMARY KEY,
    category    TEXT         NOT NULL DEFAULT 'generic',
    risk_score  SMALLINT     NOT NULL DEFAULT 50
                CHECK (risk_score BETWEEN 0 AND 100),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE role_prefixes IS 'Local-parts genéricos (info, support, admin, etc.)';

-- Seed inicial (BR + EN)
INSERT INTO role_prefixes (prefix, category, risk_score) VALUES
    ('admin',          'administrative',   80),
    ('administrator',  'administrative',   80),
    ('root',           'administrative',   85),
    ('contact',        'generic',          60),
    ('contato',        'generic',          60),
    ('info',           'generic',          70),
    ('hello',          'generic',          60),
    ('mail',           'generic',          70),
    ('email',          'generic',          70),
    ('postmaster',     'rfc_required',     90),
    ('hostmaster',     'rfc_required',     90),
    ('webmaster',      'rfc_required',     90),
    ('abuse',          'rfc_required',     90),
    ('noreply',        'no_reply',         95),
    ('no-reply',       'no_reply',         95),
    ('naoresponder',   'no_reply',         95),
    ('nao-responder',  'no_reply',         95),
    ('donotreply',     'no_reply',         95),
    ('do-not-reply',   'no_reply',         95),
    ('support',        'support',          70),
    ('suporte',        'support',          70),
    ('sac',            'support',          70),
    ('atendimento',    'support',          70),
    ('help',           'support',          70),
    ('ajuda',          'support',          70),
    ('sales',          'commercial',       60),
    ('vendas',         'commercial',       60),
    ('marketing',      'commercial',       60),
    ('comercial',      'commercial',       60),
    ('billing',        'financial',        70),
    ('financeiro',     'financial',        70),
    ('cobranca',       'financial',        70),
    ('hr',             'human_resources',  70),
    ('rh',             'human_resources',  70),
    ('careers',        'human_resources',  60),
    ('jobs',           'human_resources',  60),
    ('vagas',          'human_resources',  60),
    ('press',          'media',            60),
    ('imprensa',       'media',            60),
    ('media',          'media',            60),
    ('news',           'media',            60),
    ('newsletter',     'marketing',        75),
    ('notifications',  'system',           85),
    ('alerts',         'system',           85),
    ('alertas',        'system',           85),
    ('system',         'system',           85),
    ('sistema',        'system',           85),
    ('robot',          'system',           90),
    ('bot',            'system',           90),
    ('mailer-daemon',  'system',           95),
    ('postmaster',     'rfc_required',     90)
ON CONFLICT (prefix) DO NOTHING;
